---
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Launchpad
- Safari
- Messages
- Mail
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Reminders
- Notes
- TV
- Music
- Podcasts
- News
- 'App Store'
dockitems_persist: 
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
  pos: 1
- name: "Opera"
  path: "/Applications/Opera.app/"
  pos: 2
- name: "Firefox"
  path: "/Applications/Firefox.app/"
  pos: 3
- name: "KeePassXC"
  path: "/Applications/KeePassXC.app/"
  pos: 4
- name: "System Settings"
  path: "/Applications/System Settings.app/"
  pos: 5
- name: "kitty"
  path: "/Applications/kitty.app/"
  pos: 6


configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/matruim/dotfiles
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .gitconfig

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - asdf
  - gettext
  - git
  - github/gh/gh
  - gpg
  - pinentry-mac
  - libevent
  - sqlite
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - zsh-history-substring-search

homebrew_uninstalled_packages: []

homebrew_taps: []
  # - homebrew/core
  # - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - azure-data-studio
  - docker
  - dropbox
  - firefox
  - google-chrome
  - kitty
  - keepassxc
  - rectangle
  - opera
  - visual-studio-code
  - intellij-idea
  - figma
  - bartender
  - iina

homebrew_cask_accept_external_apps: true


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 497799835, name: "Xcode (14.1)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: 
  - name: sass
    state: latest

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []